support for multiple cities

diff --git a/wttr b/wttr
--- a/wttr
+++ b/wttr
@@ -33,6 +33,20 @@ check_values() {
     fi
 }
 
+print() {
+    local msg="$1"
+    local level="$2"
+    if [[ $SILENT -eq 1 ]]; then return; fi
+    if [[ "$level" == "debug" && $DEBUG -ne 1 ]]; then return; fi
+
+    if [[ "$level" == "error" ]]; then
+        >&2 printf -- "${msg}\n"
+    else
+        printf -- "${msg}\n"
+    fi
+}
+
+
 CITY="$(config_get DEFAULT_LOCATION '')"
 OUTPUT="$(config_get OUTPUT 'auto')"
 UNITS="$(config_get UNITS 'auto')"
@@ -41,7 +55,7 @@ FORMAT="$(config_get FORMAT, '')"
 SILENT=0
 PLAIN=0
 DEBUG=0
-
+CITIES_ARR=()
 
 # see https://unix.stackexchange.com/questions/129391/passing-named-arguments-to-shell-scripts
 # for reference
@@ -52,8 +66,8 @@ while [ $# -gt 0 ]; do
             CITY="${1#*=}"
             ;;
         --debug)
-                DEBUG=1
-                ;;
+            DEBUG=1
+            ;;
         --engine|-e)
             if [[ "$1" != *=* ]]; then shift; fi
             ENGINE="${1#*=}"
@@ -71,11 +85,11 @@ while [ $# -gt 0 ]; do
             OUTPUT="${1#*=}"
             ;;
         --plain)
-                PLAIN=1
-                ;;
+            PLAIN=1
+            ;;
         --silent)
-                SILENT=1
-                ;;
+            SILENT=1
+            ;;
         --text|-t)
             OUTPUT="text"
             ;;
@@ -84,25 +98,24 @@ while [ $# -gt 0 ]; do
             UNITS="${1#*=}"
             ;;
         *)
-            print "Error: Invalid argument $1" "error"
-            exit 1
+            if [[ "$1" == -* ]]; then
+                print "Error: Invalid argument $1" "error"
+                exit 1
+            else
+                CITIES_ARR+=("$1")
+            fi
             ;;
     esac
     shift
 done
 
-print() {
-    local msg="$1"
-    local level="$2"
-    if [[ $SILENT -eq 1 ]]; then return; fi
-    if [[ "$level" == "debug" && $DEBUG -ne 1 ]]; then return; fi
-
-    if [[ "$level" == "error" ]]; then
-        >&2 printf -- "${msg}\n"
-    else
-        printf -- "${msg}\n"
-    fi
-}
+printf -v joined '%s,' "${CITIES_ARR[@]}"
+printf -v CITIES "${joined%,}"
+if [[ "$CITIES" == "" ]]; then CITIES="$CITY"; fi
+CITIES=$(echo "$CITIES" | sed -r 's/ /\+/g')
+if echo "$CITIES" | grep -q ,; then
+    CITIES="{${CITIES}}"
+fi
 
 ALLOWED_UNITS=('u' 'm' 'M' 'auto')
 ALLOWED_OUTPUTS=('auto' 'text' 'png' 'json')
@@ -110,9 +123,8 @@ ALLOWED_OUTPUTS=('auto' 'text' 'png' 'json')
 check_values "$UNITS" "${ALLOWED_UNITS[@]}"
 check_values "$OUTPUT" "${ALLOWED_OUTPUTS[@]}"
 
-CITY=$(echo "$CITY" | sed -r 's/ /\+/g')
 EXEC="$ENGINE"
-URL="https://wttr.in/${CITY}"
+URL="https://wttr.in/${CITIES}"
 PARAMS=""
 
 print "--${OUTPUT}--" "debug"
